### ISSUE TITLE
Got NumberFormatException when login just finished

### ISSUE THREAD

**Issue by JxSun** [xiaomi-passport/oauth-android-sdk#6]
W/XiaomiOAuthResults: error, return 0 instead:
                                                                                             java.lang.NumberFormatException: Invalid int: "null"
                                                                                                 at java.lang.Integer.invalidInt(Integer.java:138)
                                                                                                 at java.lang.Integer.parseInt(Integer.java:358)
                                                                                                 at java.lang.Integer.parseInt(Integer.java:334)
                                                                                                 at com.xiaomi.account.openauth.XiaomiOAuthResults.getIntCompatibly(XiaomiOAuthResults.java:149)
                                                                                                 at com.xiaomi.account.openauth.XiaomiOAuthResults.parseBundle(XiaomiOAuthResults.java:199)
                                                                                                 at com.xiaomi.account.openauth.XiaomiOAuthorize$XiaomiTokenFuture.set(XiaomiOAuthorize.java:198)
                                                                                                 at com.xiaomi.account.openauth.XiaomiOAuthorize$XiaomiTokenFuture$2.onResult(XiaomiOAuthorize.java:232)
                                                                                                 at com.xiaomi.account.XiaomiOAuthResponse.setIXiaomiAuthResponseResult(XiaomiOAuthResponse.java:69)
                                                                                                 at com.xiaomi.account.XiaomiOAuthResponse.onResult(XiaomiOAuthResponse.java:37)
                                                                                                 at com.xiaomi.account.openauth.AuthorizeActivityBase.setResultAndFinish(AuthorizeActivityBase.java:164)
                                                                                                 at com.xiaomi.account.openauth.AuthorizeActivityBase.setResultAndFinish(AuthorizeActivityBase.java:151)
                                                                                                 at com.xiaomi.account.openauth.AuthorizeActivityBase$AuthorizeWebViewClient.shouldOverrideUrlLoading(AuthorizeActivityBase.java:358)
                                                                                                 at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:342)
                                                                                                 at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:168)
                                                                                                 at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:256)
                                                                                                 at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                                                 at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7230)
                                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Moonant** [comment]
just a warn , ignore
